apiVersion: v1
kind: PersistentVolume
metadata:
  name: altermanager-pv
  namespace: kube-system
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/nfs/alertmanager
    server: 172.17.80.29
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: altermanager-pvc
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Mi
