apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: kube-system
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/nfs/prometheus
    server: 172.17.80.29
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-pvc
  namespace: kube-system
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
